name: creditcard_fraud_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - notebook
  - nb_conda_kernels
  - nb_conda
  - ipython=8.24.0
  - statsmodels
  - jupyter_contrib_nbextensions
  - jupyterlab_widgets
  - nodejs
  - pip=24.0
  - pip:
    - imbalanced-learn
    - widgetsnbextension
    - voila==0.5.6
    - bqplot
    - plotly
